### PR TITLE
Docs: Resolve various typos

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Fix various typos.

## Details
I found the first few manually in the README, and then found the rest via `codespell`.

## Note
There's another typo which seems more critical to the behaviour of the package, so I did not change that one:
https://github.com/huggingface/optimum-benchmark/blob/90ad2ea78d23ad59ef23ee9552a1c484706ec336/optimum_benchmark/benchmarks/training/benchmark.py#L53

`samles` should be `samples`. Because of this, a bunch of the csv's also have this `samles`: https://github.com/huggingface/optimum-benchmark/blob/90ad2ea78d23ad59ef23ee9552a1c484706ec336/examples/training-llamas/experiments/A100-80GB/llama_peft%2Bbnb_batch_size(2)/1/training_results.csv

I'll leave this one for you to fix, as I'm not sure how it all connects together.

- Tom Aarsen

### CODE REVIEW

**Comment by IlyasMoutawwakil** [comment]
Thanks a lott! definitely need to integrate a `codespell` workflow!

**Comment by IlyasMoutawwakil** [comment]
@tomaarsen can you run `make style`

**Comment by tomaarsen** [comment]
Of course! Done. 

And don't bother with integrating `codespell` in a CI or something - it makes a lot of mistakes too, so it requires a manual look :)

**Comment by tomaarsen** [comment]
Oh, I'm probably using a different version of black

**Comment by IlyasMoutawwakil** [comment]
Thanks

**Pull request merged**
